name: Deploy-to-prod

on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: 'Install, test and build'
        run: |
          npm ci
          npm test
          npm build

      - name: 'Publish'
        run: |
          npm version ${{ steps.get-latest-tag.outputs.tag }} --no-git-tag-version
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
